Repository Khushii-Arora/Hacktober_Fest_webDev_Project, pull requests merged in 2022-10, with the labels that each got.

#2 skill section added
  index.html
Labels: Hacktoberfest

#3 minor changes and bg img change
  assets/img/hero-bg.jpg
  assets/img/profile-img.jpg
  index.html
Labels: Hacktoberfest, Hacktoberfest2022

#4 Fact Section added
  index.html
Labels: Hacktoberfest, Hacktoberfest2022, hacktoberfest-accepted

#6 Resume Section Added
  index.html
Labels: Hacktoberfest, Hacktoberfest2022, hacktoberfest-accepted

#7 Updated Readme: Resume section completed
  README.md
Labels: documentation, Hacktoberfest, Hacktoberfest2022, hacktoberfest-accepted

#8 portfolio section added
  index.html
Labels: Hacktoberfest, Hacktoberfest2022, hacktoberfest-accepted

#10 Updated portfolio contribution details in ReadMe
  README.md
Labels: documentation, Hacktoberfest, Hacktoberfest2022, hacktoberfest-accepted

#11 Contact page added & merged with Linktree page
  index.html
Labels: Hacktoberfest, Hacktoberfest2022, hacktoberfest-accepted

#13 UI Improved
  assets/css/style.css
Labels: Hacktoberfest, Hacktoberfest2022, hacktoberfest-accepted

#16 Updated styles.css
  assets/css/style.css
Labels: Hacktoberfest, Hacktoberfest2022, hacktoberfest-accepted

#17 Added the services section
  assets/css/style.css
  index.html
Labels: Hacktoberfest, Hacktoberfest2022, hacktoberfest-accepted
